### ISSUE TITLE
Error: Request failed with status code 429

### ISSUE THREAD

**Issue by theskywilldawn** [TomLBZ/koishi-plugin-openai#10]
一段时间内调用api次数过多导致的，但是无论等多久，发送任何内容，始终报错Error: Request failed with status code 429。
希望能增加一个重置线程Reset Thread的功能。

**Comment by wochenlong** [comment]
我也遇到了这个问题，日志显示“ Error: Request failed with status code 429”，为了找出原因，我尝试了很多办法，其中一个解决办法是换另一个openai账号的api，这很有效，openai插件立马就可以使用了，或许可以在某种程度上解决这个问题

**Comment by theskywilldawn** [comment]
> 其实这个问题是openAI上的免费额度用完导致的，同一个账号申请多个API依然会有这个问题。每个新账号有18USD的额度，但是davinci模型的api相当贵，我把这个扔给群友玩，一天就用掉了8USD

**Comment by unclejjjj** [comment]
我换了新的根本没用啊，求救！！

**Comment by TomLBZ** [comment]
我自己也时不时连不上openai的api（人在国外）。所以感觉应该是capacity的问题………………
目前只能试着重启插件/等待/换api了……
