### ISSUE TITLE
max_token问题

### ISSUE THREAD

**Issue by Kiyliy** [TomLBZ/koishi-plugin-openai#12]
max_token官网给的最大值不是4000吗,davinci-003,为什么这里最多只能选择512哇
另外,希望机器人在发送消息的时候艾特并且回复一下触发机器人的那条消息

**Comment by TomLBZ** [comment]
max_token的长度是全部的token，然而他还要包含一大堆其他东西，比如人设、消息记录，等等。而且回复的token数也是从这4000里面扣除。因此，非常不建议把这个数字开大……
至于at出发回复的消息，已提上日程啦

**Comment by TomLBZ** [comment]
> 另外,希望机器人在发送消息的时候艾特并且回复一下触发机器人的那条消息

在（ver.2.0.1）中已添加该功能~~~///(^v^)\\\~~~
