### ISSUE TITLE
api无法调用

### ISSUE THREAD

**Issue by spqdem** [TomLBZ/koishi-plugin-openai#15]
从3.2号下午起，openai官网大概墙了api调用

**Comment by TomLBZ** [comment]
兴许大概需要全局代理（？）

**Comment by spqdem** [comment]
问题已经解决，在clash里面新建规则，添加openai.com，然后选DOMAIN-SUFFIX，然后在koishi的根目录下找到并更改node_modules\openai\dist\common.js，在第146行替换成
const axiosRequestArgs = Object.assign(Object.assign({}, axiosArgs.options), { url: ((configuration === null || configuration === void 0 ? void 0 : configuration.basePath) || basePath) + axiosArgs.url , proxy: { protocol: 'socks5', host: '127.0.0.1', port: 7890 }});
重新登录koishi并使用clash规则代理即可。

**Comment by TomLBZ** [comment]
> 问题已经解决，在clash里面新建规则，添加openai.com，然后选DOMAIN-SUFFIX，然后在koishi的根目录下找到并更改node_modules\openai\dist\common.js，在第146行替换成
const axiosRequestArgs = Object.assign(Object.assign({}, axiosArgs.options), { url: ((configuration === null || configuration === void 0 ? void 0 : configuration.basePath) || basePath) + axiosArgs.url , proxy: { protocol: 'socks5', host: '127.0.0.1', port: 7890 }});
重新登录koishi并使用clash规则代理即可。

根据此回答，问题已解决
