### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by chqw163** [TomLBZ/koishi-plugin-openai#18]
![image](https://user-images.githubusercontent.com/43513937/223150411-0457337f-55dd-4152-803e-6ae2e59c0001.png)
开了代理，使用其他ai插件正常

**Comment by chqw163** [comment]
设置上bing的api空着，其他都填了

**Comment by TomLBZ** [comment]
#17 似乎是代理的问题。移步另一个issue。

**Comment by TomLBZ** [comment]
移步另一个issue #17
