### ISSUE TITLE
好像openai api没有name字段？

### ISSUE THREAD

**Issue by yi03** [TomLBZ/koishi-plugin-openai#22]
看了看文档好像openai api没有name字段，也许可以去掉？虽然加上也不影响什么（

**Comment by TomLBZ** [comment]
这个是战未来的字段。虽然Doc没写，但是我从他们的库代码里面看到了。未来或许会开放。目前如果这个字段胡乱设置是会引起invalid response的。未来预计会用于多角色在同一个context下对话。
