### ISSUE TITLE
使用网络搜索时，机器人返回结果更偏向于回答网络搜索结果而不是实际聊天对话

### ISSUE THREAD

**Issue by lingyunytc** [TomLBZ/koishi-plugin-openai#24]
![image](https://user-images.githubusercontent.com/61460076/223355561-f31fa7b9-b76e-4407-93e1-4c70058efea7.png)
![image](https://user-images.githubusercontent.com/61460076/223355651-d4b45c07-e665-4884-9ff6-c814feff8e92.png)
![image](https://user-images.githubusercontent.com/61460076/223355808-54502bbb-a15c-47e4-abdc-8932d26fbc9d.png)
![image](https://user-images.githubusercontent.com/61460076/223356263-68ae4d0d-f41e-477c-8fcf-99e2de30b4d9.png)

**Comment by Pafffffff** [comment]
一个建议，现在调用搜索模块机器人响应太慢了，有时候甚至到十秒，希望可以把搜索设为可选功能。

**Comment by TomLBZ** [comment]
@Pafffffff 根据我的timing记录，OpenAI调用与Pinecone与Search的耗时占比大约是6:3:1

**Comment by TomLBZ** [comment]
> @Pafffffff 根据我的timing记录，OpenAI调用与Pinecone与Search的耗时占比大约是6:3:1

而且openai的api有时候甚至有概率返回个500或者501什么的

**Comment by TomLBZ** [comment]
@Pafffffff 
[看样子是OpenAI的问题](https://community.openai.com/t/laggy-or-error-for-gpt-3-5-turbo/87207)

**Comment by TomLBZ** [comment]
ver 2.0.5 已修复
