### ISSUE TITLE
网络搜索功能开关

### ISSUE THREAD

**Issue by lingyunytc** [TomLBZ/koishi-plugin-openai#27]
是否可以给网络搜索功能增加一个开关，最新的版本网络搜索对对话的影响改善了不少，但有时突然来一句有点出戏
![223708236-a5bf9914-d414-4ad1-a8b7-5abc42494182](https://user-images.githubusercontent.com/61460076/223709191-361ed2d2-65a7-4fb1-a718-e0cc18914c74.png)
还有就是问着问着，就会不回复
![image](https://user-images.githubusercontent.com/61460076/223709799-1ca808db-63d7-4fb6-a8ad-d92dcb5d1367.png)
开了群里消息回复时艾特，就只会艾特人

**Comment by TomLBZ** [comment]
好滴，看来加个开关还是有必要的，功能在路上了，稍等哦

**Comment by TomLBZ** [comment]
开关已添加
