### ISSUE TITLE
时间

### ISSUE THREAD

**Issue by ya-zhe** [TomLBZ/koishi-plugin-openai#5]
可以加一个同步时间吗 我对AI提出同步时间 但同步的时间是2020年 提出了同步指定时间 但还是会提示时间是2020年

**Comment by TomLBZ** [comment]
好的，下一次更新会加上对当前时间的感知👌

**Comment by TomLBZ** [comment]
GPT经常性口胡，不过我尽力了：
![image](https://user-images.githubusercontent.com/26886705/223084465-f9ad6146-6a2b-4726-a598-917732f70445.png)
