### ISSUE TITLE
网络异常或服务器关闭。

### ISSUE THREAD

**Issue by lychees** [TomLBZ/koishi-plugin-openai#9]
RT

**Comment by MirrorCY** [comment]
你发错仓库了，这个是 openchat 的报错提示（

**Comment by MirrorCY** [comment]
现在 openchat 已全面转为自建，可以关注 [上游 issue](https://github.com/acheong08/ChatGPT/issues) 及 [discord 群组](https://discord.gg/DzHA2hqMuM) 以获得服务可用性通知，你可以关闭此 issue 了

**Comment by MirrorCY** [comment]
cc @TomLBZ

**Comment by TomLBZ** [comment]
不属于这个仓库
